name: mepbm CI test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        sudo apt-get install --fix-missing doxygen graphviz libboost-all-dev numdiff -y
        doxygen --version
        git clone https://github.com/bangerth/SampleFlow.git
        wget https://gitlab.com/libeigen/eigen/-/archive/3.3.9/eigen-3.3.9.tar.gz
        tar zxf eigen-3.3.9.tar.gz eigen
        mkdir ./eigen/build
        mkdir ./eigen/install
        cd ./eigen/build
        cmake ../ -DCMAKE_INSTALL_PREFIX=../install
        make install
        cd ../../
        mkdir sundials
        cd ./sundials
        wget https://github.com/LLNL/sundials/releases/download/v5.7.0/sundials-5.7.0.tar.gz
        tar zxf sundials-5.7.0.tar.gz
        cd sundials-5.7.0
        mkdir ./build
        mkdir ./install
        cd ./build
        cmake ../ -DCMAKE_INSTALL_PREFIX=../install
        make install
    - name: cmake
      run: cmake -DSAMPLEFLOW_DIR="$PWD/SampleFlow" -DEIGEN_DIR="$PWD/eigen/install" -DSUNDIALS_DIR="$PWD/sundials/sundials-5.7.0/install" -DCMAKE_BUILD_TYPE=release .
    - name: build
      run: make
    - name: ctest
      run: ctest --output-on-failure -j2
