name: mepbm CI test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        sudo apt-get install doxygen graphviz libboost-all-dev numdiff -y
        doxygen --version
        git clone https://github.com/bangerth/SampleFlow.git
        git clone https://gitlab.com/libeigen/eigen.git
        mkdir ./eigen/build
        mkdir ./eigen/install
        cd ./eigen/build
        cmake ../ -DCMAKE_INSTALL_PREFIX=../install
        make install
        cd ../../
    - name: cmake
      run: cmake -DSAMPLEFLOW_DIR="$PWD/SampleFlow" -DEIGEN_DIR="$PWD/eigen/install" -DCMAKE_BUILD_TYPE=release .
    - name: build
      run: make
    - name: ctest
      run: ctest --output-on-failure -j2
    - name: check on failed test
      run: ./tests/log_likelihood_reasonable_ode_float
